name: Deploy to S3

on:
  push:
    branches:
      - Production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm install
        echo "Dependencies installed."

    - name: Build project
      run: |
        echo "Building the project..."
        npm run build
        echo "Build complete."

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.7
      with:
        args: --delete --acl public-read
      env:
        SOURCE_DIR: 'build'
        AWS_S3_BUCKET: 'app.agino.tech'
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
